HomeworkProject1/Models/ErrorViewModel.cs
using System;

namespace HomeworkProject1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HomeworkProject1/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HomeworkProject1.Models
{
    public class Staff
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string Department { get; set; }
        [Required]
        public string Title  { get; set; }
        public string Address { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime BirthDate { get; set; }
        [Required]
        public string Image { get; set; }
        public static List<Staff> GetSampleData()
        {
            var person1 = new Staff
            {
                Id = 1,
                Name = "Emre",
                Surname = "Ekiz",
                Department = "Bilgi İşlem",
                Title = "Bilgisayar Mühendisi",
                Address = "1530 County Rd #155, Post, TX, 79356",
                StartDate = Convert.ToDateTime("01.01.2015"),
                BirthDate = Convert.ToDateTime("26.08.1995"),
                Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxKlQbecwqKkurzvZ20x6Ta0WCpD97Z1zsUfLZF7HGx-gfd1Mc"
               


            };
            var person2 = new Staff
            {
                Id = 2,
                Name = "Erdem",
                Surname = "Ekiz",
                Department = "Pazarlama",
                Title = "Satış Sorumlusu",
                Address = "742 Aspen Cir, Red Hill, PA, 18076",
                StartDate = Convert.ToDateTime("23.05.2017"),
                BirthDate = Convert.ToDateTime("11.03.1992"),
                Image = "https://image.shutterstock.com/image-vector/man-character-face-avatar-glasses-260nw-542759665.jpg"


            };
            var person3 = new Staff
            {
                Id = 3,
                Name = "Ömer",
                Surname = "Ekiz",
                Department = "Üretim",
                Title = "Üretim Müdürü",
                Address = "742 Aspen Cir, Red Hill, PA, 18076",
                StartDate = Convert.ToDateTime("11.02.2015"),
                BirthDate = Convert.ToDateTime("08.01.1963"),
                Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS59TrTGVMf7FVScv2aopiEKDWa0U6EMQXiCvQ3b-rr9xuul6ov"


            };
            List<Staff> sampleData=new List<Staff>();
            sampleData.Add(person1);
            sampleData.Add(person2);
            sampleData.Add(person3);

            return sampleData;
        }

    }

   
}

HomeworkProject1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HomeworkProject1.Models;

namespace HomeworkProject1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HomeworkProject1/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeworkProject1.Models;
using Microsoft.AspNetCore.Mvc;

namespace HomeworkProject1.Controllers
{
    public class StaffController : Controller
    {
        
        public static List<Staff> staffs;
        public IActionResult Index()
        {
            List<Staff> staffList = Staff.GetSampleData();
            if (staffs != null && staffs.Any())
            {
                staffList.AddRange(staffs);
            }
            return View(staffList);
          
        }

        public IActionResult Detail(int id)
        {
            List<Staff> staffList = Staff.GetSampleData();
            if (staffs != null && staffs.Any())
            {
                staffList.AddRange(staffs);
            }
            Staff item = staffList.Where(x => x.Id == id).FirstOrDefault();
            return View(item);

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Staff modelStaff)
        {
            if (ModelState.IsValid)
            {
                if (staffs==null)
                {
                    staffs=new List<Staff>();
                }
                staffs.Add(modelStaff);
                return RedirectToAction("Detail", new {id = modelStaff.Id});
            }

            return View(modelStaff);




        }
    }
}

HomeworkProject1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HomeworkProject1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeworkProject1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeworkProject1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Staff</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HomeworkProject1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

HomeworkProject1/Views/Staff/Create.cshtml
@model HomeworkProject1.Models.Staff

@{
    ViewData["Title"] = "Create";
}

<h1>Personel Ekle</h1>

@*<h4>Staff</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">İsim</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label">Soyisim</label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label">Departman</label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Ünvan</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Adres</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">İşe Başlangıç Tarihi</label>
                <input asp-for="StartDate" class="form-control" type="date" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label">Doğum Tarihi</label>
                <input asp-for="BirthDate" class="form-control" type="date"/>
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Fotoğraf</label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HomeworkProject1/Views/Staff/Detail.cshtml
@using Microsoft.AspNetCore.Razor.Language.Intermediate
@model HomeworkProject1.Models.Staff

@{
    ViewData["Title"] = "Detail";
}

<h1>Personel Detay</h1>

<div>
    <h4>Staff</h4>
    <hr />
    <dl class="row">
        <dd class="col-sm-12">
            @*@Html.DisplayFor(model => model.Image)*@
            <image src="@Model.Image" class="img-fluid" style="max-height:200px;"></image>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

HomeworkProject1/Views/Staff/Index.cshtml
@model IEnumerable<Staff>
@{
    ViewData["Title"] = "Index";
}

<h1>Personeller</h1>

<div>
    
    <div class="row">

        
        <div class="col-12">
            <a asp-controller="Staff" asp-action="Create" class="btn btn-primary mb-3">Yeni Kişi Ekle</a>
        </div>
        <table class="table table-striped">
            
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Adı Soyadı</th>
                    <th scope="col">Departmanı</th>
                    <th scope="col">Ünvanı</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.Name @item.Surname</td>
                        <td>@item.Department</td>
                        <td>@item.Title</td>
                        <td> <a asp-controller="Staff" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-primary">Detay</a></td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>